

CREATE TABLE artists(
id INT AUTO_INCREMENT NOT NULL,
artistname VARCHAR(128) NOT NULL UNIQUE,
PRIMARY KEY(id)
);

CREATE TABLE albums(
id INT AUTO_INCREMENT NOT NULL,
name VARCHAR(128) NOT NULL,
year YEAR(4),
artist_id INT,
PRIMARY KEY(id),
FOREIGN KEY(artist_id)
REFERENCES artists(id)
);

ALTER TABLE albums(
FOREIGN KEY(artist_id)
REFERENCES artists(id)
ON UPDATE CASCADE
ON DELETE RESTRICT
);

ALTER TABLE albums DROP COLUMN IF EXISTS artist_id;

ALTER TABLE playlists(
  id INT AUTO_INCREMENT NOT NULL,
  date_created TIMESTAMP
    DEFAULT CURRENT_TIMESTAMP,
  user_id INT,
  PRIMARY KEY(id),
  FOREIGN KEY(user_id)
    REFERENCES users(id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
);

ALTER TABLE playlist DROP COLUMN id

ALTER TABLE playlists
  ADD COLUMN id INT AUTO_INCREMENT NOT NULL,
  PRIMARY KEY(id),
    FOREIGN KEY(user_id)
    REFERENCES users(id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT

ALTER TABLE playlists
  ADD (id INT AUTO_INCREMENT NOT NULL,
  PRIMARY KEY(id),
    FOREIGN KEY(user_id)
    REFERENCES users(id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
  );


CREATE TABLE songs(
  id INT AUTO_INCREMENT NOT NULL,
  title VARCHAR(255) NOT NULL,
  length INT,
  genre VARCHAR(255),
  album_id INT,
  PRIMARY KEY(id),
  FOREIGN KEY(album_id)
    REFERENCES albums(id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
);